"""empty message

Revision ID: 9a599e54e16f
Revises: 
Create Date: 2024-01-17 07:19:22.184283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a599e54e16f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_image_id', sa.Integer(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('preserve_ratio', sa.Boolean(), nullable=False),
    sa.Column('target_width', sa.Integer(), nullable=False),
    sa.Column('target_height', sa.Integer(), nullable=False),
    sa.Column('enable_ai', sa.Boolean(), nullable=False),
    sa.Column('status_started_at', sa.DateTime(), nullable=True),
    sa.Column('status_ended_successful_at', sa.DateTime(), nullable=True),
    sa.Column('status_ended_failed_at', sa.DateTime(), nullable=True),
    sa.Column('status_ended_failed_error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processes')
    op.drop_table('images')
    # ### end Alembic commands ###
