/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/images": {
    /** List images */
    get: operations["__images_get"];
  };
  "/images/{id}": {
    /** Delete image */
    delete: operations["__images__id__delete"];
  };
  "/images/upload-local": {
    /** Upload local images */
    post: operations["__images_upload_local_post"];
  };
  "/images/thumbnail/{id}.webp": {
    /** Image thumbnail (144x144) */
    get: operations["__images_thumbnail__id__webp_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Body___images_upload_local_post */
    Body___images_upload_local_post: {
      /** Files */
      files: string[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ImageODto */
    ImageODto: {
      /** Id */
      id: number;
      /** Src */
      src: string;
      /** Name */
      name: string;
      source: components["schemas"]["ImageSizeDto"];
    };
    /** ImageSizeDto */
    ImageSizeDto: {
      /** Width */
      width: number;
      /** Height */
      height: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** List images */
  __images_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ImageODto"][];
        };
      };
    };
  };
  /** Delete image */
  __images__id__delete: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ImageODto"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Upload local images */
  __images_upload_local_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body___images_upload_local_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ImageODto"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Image thumbnail (144x144) */
  __images_thumbnail__id__webp_get: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
